market_data_platform:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'SYSADMIN') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'DATAPIPELINE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'DATAPIPELINE_WH') }}"
      schema: SILVER
      threads: 4
  target: dev
