name: datapipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # Kafka
  - confluent-kafka
  # Data processing
  - pyarrow
  - fastavro
  # AWS
  - boto3
  # Snowflake
  - snowflake-connector-python
  # Utilities
  - python-dotenv
