version: 2

sources:
  - name: DATAPIPELINE
    database: DATAPIPELINE
    schema: TRADES
    tables:
      - name: RAW_TRADES
        freshness:
          warn_after: {count: 5, period: minute}
          error_after: {count: 10, period: minute}